"""create vouchers

Revision ID: 72a5141f0f13
Revises: 
Create Date: 2025-08-01 13:18:59.010365

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72a5141f0f13'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('voucher',
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('duration', sa.String(length=2), nullable=False),
    sa.Column('used', sa.Boolean(), sa.CheckConstraint('used in (0,1)'), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('voucher')
    # ### end Alembic commands ###
